trigger:
  branches:
    include:
      - main

variables:
  sonarProjectKey: 'simple-cicd-demo'

stages:
- stage: BuildAndDeploy
  displayName: 'SonarQube Scan and Deploy'
  jobs:
  - job: ScanAndDeploy
    displayName: 'Run SonarQube and Deploy to EC2'
    pool:
      vmImage: 'ubuntu-latest'

    steps:
    - checkout: self

    # Prepare SonarQube analysis (uses service connection)
    - task: SonarQubePrepare@5
      inputs:
        SonarQube: 'MySonarQubeConnection'   # Your SonarQube service connection name
        scannerMode: 'CLI'
        configMode: 'manual'
        cliProjectKey: $(sonarProjectKey)
        cliSources: '.'

    # Run SonarQube analysis
    - task: SonarQubeAnalyze@5

    # Publish SonarQube results
    - task: SonarQubePublish@5
      inputs:
        pollingTimeoutSec: '300'

    # Copy files to EC2 dest_inst
    - task: CopyFilesOverSSH@0
      inputs:
        sshEndpoint: 'ec2-dest-ssh'         # Your SSH service connection name
        sourceFolder: '$(Build.SourcesDirectory)'
        contents: '**/*'
        targetFolder: '/var/www/html'
        cleanTargetFolder: true
        overwrite: true
      displayName: 'Copy files to EC2 destination'

    # Restart Apache on EC2
    - task: SSH@0
      inputs:
        sshEndpoint: 'ec2-dest-ssh'
        runOptions: 'commands'
        commands: |
          sudo systemctl restart httpd
      displayName: 'Restart Apache on EC2'
