trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
  EC2_HOST: '44.211.44.22'
  EC2_USER: 'ec2-user'

stages:
- stage: Deploy
  displayName: 'Deploy to EC2'
  jobs:
  - job: CopyHTML
    displayName: 'Copy HTML Files to EC2'
    steps:

    # Install the PEM key securely
    - task: InstallSSHKey@0
      name: InstallEC2Key
      inputs:
        sshPublicKey: ''  # not needed
        sshKeySecureFile: 'app.pem'  # MUST match exact name in Secure Files
        knownHostsEntry: '$(EC2_HOST)'

    # Confirm the key is downloaded
    - script: |
        echo "Checking temp directory for PEM file..."
        ls -l $(Agent.TempDirectory)
      displayName: 'Debug: List Agent.TempDirectory'

    # Copy HTML files
    - script: |
        echo "Copying files to EC2..."
        scp -i $(Agent.TempDirectory)/app.pem -o StrictHostKeyChecking=no -r *.html $(EC2_USER)@$(EC2_HOST):/var/www/html/site
      displayName: 'SCP HTML Files to EC2'
