trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
  EC2_HOST: '52.202.2.0'
  EC2_USER: 'ec2-user'

stages:
- stage: Deploy
  jobs:
  - job: CopyHTML
    steps:

    # Step 1: Install SSH key to authenticate to EC2
    - task: InstallSSHKey@0
      inputs:
        sshKeySecureFile: 'app.pem'
        knownHostsEntry: '$(EC2_HOST)'

    # Step 2: (Optional) Debug: show temp folder
    - script: |
        ls -l $(Agent.TempDirectory)
      displayName: 'Debug: Show PEM file'

    # Step 3: Deploy HTML files via SCP
    - script: |
        echo "Deploying files to EC2..."
        scp -i $(Agent.TempDirectory)/app.pem -o StrictHostKeyChecking=no -r *.html $(EC2_USER)@$(EC2_HOST):/var/www/html/site
      displayName: 'Copy HTML to EC2'
