trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
  EC2_USER: 'ec2-user'
  EC2_HOST: '$(ec2Ip)'           # Set this as a pipeline variable in Azure DevOps
  SONARQUBE_PROJECT_KEY: 'simple-html-site'

stages:
- stage: AnalyzeAndDeploy
  displayName: 'Run SonarQube Analysis and Deploy to EC2'
  jobs:
  - job: AnalyzeAndDeployJob
    displayName: 'SonarQube Scan and Deploy'
    steps:

    # Force the build branch variable to main to avoid branch analysis errors
    - script: |
        echo "##vso[task.setvariable variable=BUILD_SOURCEBRANCH]refs/heads/main"
      displayName: 'Force build branch to main'

    # Prepare SonarQube scanner (no branch info set)
    - task: SonarQubePrepare@6
      inputs:
        SonarQube: 'SonarQubeService'  # Your SonarQube service connection name
        scannerMode: 'CLI'
        configMode: 'manual'
        cliProjectKey: '$(SONARQUBE_PROJECT_KEY)'
        cliSources: '.'

    # Run SonarQube analysis
    - task: SonarQubeAnalyze@6

    # Publish SonarQube results
    - task: SonarQubePublish@6
      inputs:
        pollingTimeoutSec: '300'

    # Install SSH key for EC2
    - task: InstallSSHKey@0
      inputs:
        sshKeySecureFile: 'app.pem'
        knownHostsEntry: '$(EC2_HOST)'

    # Debug PEM presence (optional)
    - script: |
        ls -l $(Agent.TempDirectory)
      displayName: 'Check SSH key file presence'

    # Deploy HTML files to EC2 using SCP
    - script: |
        echo "Deploying HTML files to EC2..."
        scp -i $(Agent.TempDirectory)/app.pem -o StrictHostKeyChecking=no -r *.html $(EC2_USER)@$(EC2_HOST):/var/www/html/site
      displayName: 'Deploy HTML to EC2'
