trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
  EC2_USER: 'ec2-user'
  EC2_HOST: '$(ec2Ip)'  # Set as variable in pipeline UI

stages:
- stage: DeployToEC2
  jobs:
  - job: Deploy
    steps:
    - checkout: self

    - task: InstallSSHKey@0
      inputs:
        sshKeySecureFile: 'app.pem'       # Make sure this is uploaded in Secure Files
        knownHostsEntry: '$(EC2_HOST)'

    - script: |
        echo "Deploying HTML files to EC2..."
        scp -i $(Agent.TempDirectory)/app.pem -o StrictHostKeyChecking=no -r *.html $(EC2_USER)@$(EC2_HOST):/var/www/html/site
      displayName: 'Copy HTML Files to EC2'
