trigger:
  branches:
    include:
      - main

variables:
  sonarProjectKey: 'simple-cicd-demo'

stages:
- stage: BuildAndDeploy
  displayName: 'SonarQube Scan and Deploy'
  jobs:
  - job: ScanAndDeploy
    displayName: 'Run SonarQube and Deploy to EC2'
    pool:
      vmImage: 'ubuntu-latest'

    steps:
    - checkout: self

    # Optional: Show file structure for debugging
    - script: |
        echo "=== W
