trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
  EC2_USER: 'ec2-user'
  EC2_HOST: '$(ec2Ip)'  # Set in pipeline variables
  SONARQUBE_PROJECT_KEY: 'simple-html-site'

stages:
- stage: AnalyzeAndDeploy
  jobs:
  - job: RunPipeline
    steps:
    - task: SonarQubePrepare@6
      inputs:
        SonarQube: 'SonarQubeService'    # Your SonarQube service connection name
        scannerMode: 'CLI'
        configMode: 'manual'
        cliProjectKey: '$(SONARQUBE_PROJECT_KEY)'
        cliSources: '.'
        extraProperties: |
          sonar.verbose=true
          sonar.log.level=DEBUG

    - task: SonarQubeAnalyze@6

    - task: SonarQubePublish@6
      inputs:
        pollingTimeoutSec: '300'

    - task: InstallSSHKey@0
      inputs:
        sshKeySecureFile: 'app.pem'       # Your uploaded private key in Secure Files
        knownHostsEntry: '$(EC2_HOST)'

    - script: |
        echo "Deploying HTML files to EC2..."
        scp -i $(Agent.TempDirectory)/app.pem -o StrictHostKeyChecking=no -r *.html $(EC2_USER)@$(EC2_HOST):/var/www/html/site
      displayName: 'Deploy HTML to EC2'
