trigger:
- main

variables:
  SONAR_TOKEN: $(SONAR_TOKEN)

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: SonarQubePrepare@5
  inputs:
    SonarQube: 'MySonarQubeConnection'
    scannerMode: 'CLI'
    configMode: 'manual'
    cliProjectKey: 'simple-cicd-demo'
    cliProjectName: 'simple-cicd-demo'
    extraProperties: |
      sonar.sources=.
      sonar.branch.name=

- task: SonarQubeAnalyze@5

- task: SonarQubePublish@5
  inputs:
    pollingTimeoutSec: '300'

- task: DownloadSecureFile@1
  name: GetSSHKey
  inputs:
    secureFile: 'app.pem'

- script: |
    chmod 600 $(GetSSHKey.secureFilePath)
    scp -o StrictHostKeyChecking=no -i $(GetSSHKey.secureFilePath) *.html ec2-user@<DEST_INST_IP>:/var/www/html/
  displayName: 'Copy files to EC2 via SSH'
